### ISSUE TITLE
'init(pemRepresentation:)' is only available in iOS 14.0 or newer

### ISSUE THREAD

**Issue by yizivan** [apple/app-store-server-library-swift#25]
Hi developers,

While I tried to use this library, no matter how I change the deployment target version in my project, below error messages keeps showing during build stage. 

I can' get rid of it. 
<img width="243" alt="image" src="https://github.com/apple/app-store-server-library-swift/assets/43549544/b2ceaf80-cfac-4b02-9e7e-3f076518bc1a">
Please advise how to use this library correctly

**Comment by yizivan** [comment]
error message location:
<img width="243" alt="image" src="https://github.com/apple/app-store-server-library-swift/assets/43549544/fcbf17da-02a0-485e-a803-a5bfd1e02ca3">

**Comment by alexanderjordanbaker** [comment]
Please use version 1.0.1

**Comment by RahulMaithani** [comment]
Still facing same issue. Looks like pemRepresentation supports for iOS 14.0 version only.
![image](https://github.com/apple/app-store-server-library-swift/assets/31573878/7aaeb32a-d9a5-44a4-a655-7cb33a7ece6a)

**Comment by alexanderjordanbaker** [comment]
@RahulMaithani Sorry, this library is only meant for Swift on Server, there is not an iOS requirement. https://www.swift.org/server/

If you need to do anything on device, we recommend the StoreKit 2 framework.

**Comment by gary17** [comment]
This issue is due to incorrect `Package.swift` for `AppStoreServerLibrary`, which in version 1.0.1 reads `.iOS(.v13)`, even though the code is using iOS 14 -specific API such as `init(pemRepresentation:)`. This issue needs to be corrected by package maintainers, not by package users.

In case of such an internal package inconsistency, it is NOT sufficient to specify the `iOS Deployment Target` of `iOS 14` (or higher) in a parent Xcode project; it is necessary to patch `Package.swift` from `.iOS(.v13)` to `.iOS(.v14)` in the package checkout directory, e.g. `/Users/user/Library/Developer/Xcode/DerivedData/<project>-<build>/SourcePackages/checkouts/app-store-server-library-swift`.

Otherwise, the package builds fine under both iOS and macOS/Catalyst.

**Comment by alexanderjordanbaker** [comment]
Ah you are correct, those build targets should not be present, let me remove them, the only targets we would support would be Mac, or a server environment.

**Comment by alexanderjordanbaker** [comment]
Resolved in #29
