### ISSUE TITLE
AppReceipt verification

### ISSUE THREAD

**Issue by mefuzar** [apple/app-store-server-library-swift#41]
Hello, thank you for building a great library.

I have a question: i can see ReceiptUtility only extracting transactionId without any verification and my question: if it is being sent by client, please correct me if I am wrong: an attacker can encode any transactionId in AppReceipt structure and perform a brute attack until he/she will find a transactionId that exists and will be served by the App Store Server API.

If this is correct and we are not allowed to use verifyReceipt API endpoint - how should we verify the receipt on the server? I know how to do it with Security Framework but Swift side Server can also be run on Linux as well.

**Comment by alexanderjordanbaker** [comment]
We recommend using AppTransaction, https://developer.apple.com/documentation/storekit/apptransaction, as this is verifyable directly on server using the SignedDataVerifier class

**Comment by mefuzar** [comment]
Thank you very much... unfortunately this is not an option for our company as we must support macOS versions older than 13.0, can you please help or give us directions on how to verify AppReceipt Server-Side using Swift with Linux support? I    have checked: swift-crypto but could not figure out if it has what I need to verify DER/PKCS7 Container.

**Comment by alexanderjordanbaker** [comment]
You would need to implement the verification process as described in https://developer.apple.com/documentation/appstorereceipts/validating_receipts_on_the_device, but on your server

**Comment by mefuzar** [comment]
Yes... I know that - the question is how to do that on Linux. running on an Apple device and having access to the Security framework makes it very easy to verify the receipt file.

In other words - I am looking for a way maybe to use: swift-crypto in order to verify DER/PKCS7 file but could not figure out how...

**Comment by alexanderjordanbaker** [comment]
Hello @mefuzar, this seems to be falling outside what the library supports. For assistance with things that fall outside what this library supports, I recommend filling a ticket in Feedback Assistant (http://feedbackassistant.apple.com) for more assistance.

**Comment by mefuzar** [comment]
OK, Thank you 🙏🙏🙏

**Comment by emindeniz99** [comment]
> Hello @mefuzar, this seems to be falling outside what the library supports. For assistance with things that fall outside what this library supports, I recommend filling a ticket in Feedback Assistant (http://feedbackassistant.apple.com) for more assistance.

Hello
I think the library should handle the migration because the ReceiptUtility seems like good tool to migration but it does not do any validation of receipt.
"""
A utility that extracts transaction identifiers from receipts. The App Store Server API endpoints take a transaction identifier in the path parameter. Use this utility as you migrate from using [verifyReceipt](https://developer.apple.com/documentation/appstorereceipts/verifyreceipt) with [App Store Receipts](https://developer.apple.com/documentation/appstorereceipts) to using the App Store Server API for transaction information.
https://developer.apple.com/documentation/appstoreserverapi/simplifying_your_implementation_by_using_the_app_store_server_library
"""

"Validates authenticity of receipt" functionality is not possible on new api and the library. https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/choosing_a_receipt_validation_technique

For the developers that needs to support ios15- app receipt needs to be validated. 
So, "Validating receipts on the device" method should be implemented on the libraries(java,python,swift...).
